import { StyleSheet } from 'react-native';

const font = 'YantuSans';
const brandFont = 'YantuSansBold';

export const colors = {
  bg: '#F7F8FA',
  card: '#FFFFFF',
  text: '#1F2329',
  sub: '#646A73',
  muted: '#8F959E',
  primary: '#3370FF',
  primaryDark: '#245BDB',
  teal: '#14C9C9',
  green: '#2EA043',
  red: '#D92D20',
  orange: '#FF8F1F',
  border: '#DEE0E3',
  borderSoft: '#EFF0F1',
  chip: '#EAF2FF',
  panel: '#F2F6FF',
};

export const shadow = {
  shadowColor: '#000',
  shadowOpacity: 0.04,
  shadowRadius: 8,
  shadowOffset: { width: 0, height: 2 },
  elevation: 1,
};

export const styles = StyleSheet.create({
  app: { flex: 1, backgroundColor: colors.bg },
  screenHost: { flex: 1, overflow: 'hidden' },
  todayApp: { backgroundColor: '#F7F8FA' },
  planApp: { backgroundColor: '#F6F9FC' },
  materialApp: { backgroundColor: '#F8FAFF' },
  reviewApp: { backgroundColor: '#FBF7EF' },
  myApp: { backgroundColor: '#FAF9F5' },
  container: { padding: 16, paddingTop: 48, paddingBottom: 110 },
  materialContainer: { padding: 16, paddingTop: 48, paddingBottom: 180 },
  title: { fontFamily: brandFont, fontSize: 26, color: colors.text, marginBottom: 6 },
  h2: { fontFamily: font, fontSize: 18, color: colors.text, marginTop: 16, marginBottom: 8 },
  h3: { fontFamily: font, fontSize: 15, color: colors.text, marginBottom: 4 },
  text: { fontFamily: font, fontSize: 14, color: colors.text, lineHeight: 22 },
  sub: { fontFamily: font, fontSize: 13, color: colors.sub, lineHeight: 20 },
  tiny: { fontFamily: font, fontSize: 11, color: colors.muted },
  card: { backgroundColor: colors.card, borderRadius: 8, padding: 14, marginBottom: 10, borderWidth: 1, borderColor: colors.borderSoft, ...shadow },
  pressedSurface: { opacity: 0.78, transform: [{ scale: 0.985 }] },
  pressedChip: { opacity: 0.72, transform: [{ scale: 0.96 }] },
  pressedFab: { opacity: 0.86, transform: [{ scale: 0.94 }] },
  surface: { backgroundColor: colors.card, borderRadius: 8, borderWidth: 1, borderColor: colors.borderSoft },
  row: { flexDirection: 'row', alignItems: 'center' },
  rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  actionGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  wrap: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  segmentedRow: { flexDirection: 'row', gap: 8, backgroundColor: '#F6F7F9', borderRadius: 10, borderWidth: 1, borderColor: colors.borderSoft, padding: 4, marginBottom: 10 },
  segmentedButton: { flex: 1, minHeight: 38, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  segmentedButtonActive: { backgroundColor: colors.primary },
  segmentedButtonText: { fontFamily: font, color: colors.sub, fontSize: 13 },
  segmentedButtonTextActive: { color: '#FFFFFF' },
  chip: { paddingHorizontal: 10, paddingVertical: 6, backgroundColor: colors.chip, borderRadius: 6, marginRight: 6, marginBottom: 6 },
  chipText: { fontFamily: font, color: colors.primaryDark, fontSize: 12 },
  button: { backgroundColor: colors.primary, borderRadius: 6, paddingVertical: 12, paddingHorizontal: 14, alignItems: 'center', justifyContent: 'center' },
  buttonText: { fontFamily: font, color: '#fff', fontSize: 14 },
  secondaryButton: { borderWidth: 1, borderColor: colors.border, borderRadius: 6, paddingVertical: 11, paddingHorizontal: 14, backgroundColor: '#FFF' },
  secondaryText: { fontFamily: font, color: colors.text, fontSize: 14, textAlign: 'center' },
  dangerButton: { borderWidth: 1, borderColor: '#F3C2C2', borderRadius: 6, paddingVertical: 11, paddingHorizontal: 14, backgroundColor: '#FFF7F7' },
  dangerText: { fontFamily: font, color: colors.red, fontSize: 14, textAlign: 'center' },
  input: { fontFamily: font, borderWidth: 1, borderColor: colors.border, borderRadius: 6, padding: 12, backgroundColor: '#fff', color: colors.text, minHeight: 46, marginBottom: 8 },
  searchBox: { flexDirection: 'row', alignItems: 'center', gap: 9, borderWidth: 1, borderColor: colors.borderSoft, borderRadius: 10, paddingHorizontal: 11, backgroundColor: '#fff', minHeight: 42, marginBottom: 8, ...shadow },
  searchInput: { flex: 1, fontFamily: font, color: colors.text, minHeight: 40, paddingVertical: 8 },
  searchGlyph: { width: 22, height: 22 },
  searchGlyphCircle: { position: 'absolute', left: 1, top: 1, width: 14, height: 14, borderRadius: 7, borderWidth: 2, borderColor: colors.muted },
  searchGlyphHandle: { position: 'absolute', right: 2, bottom: 2, width: 9, height: 2, borderRadius: 99, backgroundColor: colors.muted, transform: [{ rotate: '45deg' }] },
  textarea: { fontFamily: font, borderWidth: 1, borderColor: colors.border, borderRadius: 6, padding: 12, backgroundColor: '#fff', color: colors.text, minHeight: 140, textAlignVertical: 'top', marginBottom: 8 },
  tabbar: { position: 'absolute', left: 10, right: 10, bottom: 12, height: 72, backgroundColor: '#fff', borderRadius: 14, paddingVertical: 7, paddingHorizontal: 8, flexDirection: 'row', justifyContent: 'space-around', borderWidth: 1, borderColor: colors.borderSoft, ...shadow },
  tab: { alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6, paddingVertical: 6, borderRadius: 10, width: 62, height: 56, borderWidth: 1, borderColor: 'transparent' },
  tabActive: { backgroundColor: colors.chip, borderColor: '#D8E8FF' },
  tabIconWrap: { width: 28, height: 26, alignItems: 'center', justifyContent: 'center', marginBottom: 2 },
  tabIcon: { fontFamily: font, fontSize: 19, color: colors.muted, lineHeight: 22 },
  tabIconActive: { color: colors.primaryDark },
  navCalendarIcon: { width: 22, height: 22, borderRadius: 5, borderWidth: 2, overflow: 'hidden' },
  navCalendarTop: { height: 5, width: '100%' },
  navCalendarTicks: { flexDirection: 'row', gap: 4, paddingTop: 5, paddingHorizontal: 4 },
  navCalendarTick: { width: 4, height: 4, borderRadius: 2 },
  navClipboardIcon: { width: 21, height: 23, borderRadius: 5, borderWidth: 2, alignItems: 'center', justifyContent: 'center', gap: 4 },
  navClipboardClip: { position: 'absolute', top: -4, width: 10, height: 6, borderRadius: 3, borderWidth: 2, backgroundColor: '#FFFFFF' },
  navIconLine: { width: 10, height: 2, borderRadius: 99 },
  navIconLineShort: { width: 7, height: 2, borderRadius: 99 },
  navFolderIcon: { width: 24, height: 20, borderRadius: 5, borderWidth: 2, marginTop: 2, overflow: 'hidden' },
  navFolderTab: { position: 'absolute', left: -2, top: -2, width: 12, height: 7, borderTopLeftRadius: 5, borderTopRightRadius: 5, borderWidth: 2 },
  navFolderFill: { position: 'absolute', left: 4, right: 4, bottom: 4, height: 3, borderRadius: 99 },
  navReviewIcon: { width: 23, height: 23, borderRadius: 12, borderWidth: 2, alignItems: 'center', justifyContent: 'center' },
  navReviewNeedle: { width: 2, height: 9, borderRadius: 99, transform: [{ rotate: '42deg' }] },
  navReviewDot: { position: 'absolute', width: 4, height: 4, borderRadius: 2, right: 4, top: 5 },
  navUserIcon: { width: 24, height: 24, alignItems: 'center', justifyContent: 'center' },
  navUserHead: { width: 9, height: 9, borderRadius: 5, borderWidth: 2, marginBottom: 2 },
  navUserBody: { width: 18, height: 10, borderTopLeftRadius: 9, borderTopRightRadius: 9, borderWidth: 2, borderBottomWidth: 0 },
  tabText: { fontFamily: font, fontSize: 11, color: colors.sub },
  tabTextActive: { color: colors.primaryDark },
  tabBadge: { position: 'absolute', right: -10, top: -5, minWidth: 17, height: 17, borderRadius: 9, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4, borderWidth: 1, borderColor: '#FFFFFF' },
  tabBadgeHot: { backgroundColor: colors.orange },
  tabBadgeText: { fontFamily: font, color: '#FFFFFF', fontSize: 9 },
  progressOuter: { height: 8, backgroundColor: '#EDF1F7', borderRadius: 99, overflow: 'hidden', marginTop: 8 },
  progressInner: { height: 8, backgroundColor: colors.primary, borderRadius: 99 },
  heroPanel: { minHeight: 180, borderRadius: 12, overflow: 'hidden', marginBottom: 12, backgroundColor: colors.panel },
  heroImage: { borderRadius: 12 },
  heroOverlay: { flex: 1, padding: 16, justifyContent: 'center', width: '58%' },
  heroEyebrow: { fontFamily: font, color: colors.primaryDark, fontSize: 12, marginBottom: 8 },
  heroTitle: { fontFamily: brandFont, color: colors.text, fontSize: 20, lineHeight: 26 },
  heroSubtitle: { fontFamily: font, color: colors.sub, fontSize: 13, lineHeight: 20, marginTop: 8 },
  metricGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 4 },
  metricTile: { flexGrow: 1, flexBasis: '31%', borderRadius: 8, padding: 12, borderWidth: 1 },
  metricTile_blue: { backgroundColor: '#F0F6FF', borderColor: '#D8E8FF' },
  metricTile_teal: { backgroundColor: '#EFFBFA', borderColor: '#CFF3EF' },
  metricTile_orange: { backgroundColor: '#FFF7ED', borderColor: '#FFE1B8' },
  metricTile_gray: { backgroundColor: '#F6F7F9', borderColor: '#E8EAED' },
  metricValue: { fontFamily: font, color: colors.text, fontSize: 20, marginBottom: 2 },
  metricLabel: { fontFamily: font, color: colors.sub, fontSize: 12 },
  commandPanel: { backgroundColor: colors.card, borderRadius: 8, padding: 16, borderWidth: 1, borderColor: colors.borderSoft, marginTop: 14, marginBottom: 12, ...shadow },
  planHeroImage: { width: '100%', height: 104, borderRadius: 10, marginBottom: 14, backgroundColor: colors.panel },
  commandEyebrow: { fontFamily: font, color: colors.primaryDark, fontSize: 12, marginBottom: 6 },
  commandTitle: { fontFamily: font, color: colors.text, fontSize: 18, lineHeight: 26, marginBottom: 4 },
  commandStats: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 12 },
  commandStat: { fontFamily: font, color: colors.sub, backgroundColor: '#F2F6FF', borderRadius: 6, paddingHorizontal: 8, paddingVertical: 5, fontSize: 12 },
  planDashboard: { backgroundColor: colors.card, borderRadius: 12, borderWidth: 1, borderColor: colors.borderSoft, overflow: 'hidden', marginTop: 14, marginBottom: 12, ...shadow },
  planDashboardImage: { width: '100%', height: 118, backgroundColor: colors.panel },
  planDashboardOverlay: { flexDirection: 'row', alignItems: 'center', gap: 12, padding: 14 },
  planProgressRing: { width: 76, height: 76, borderRadius: 38, borderWidth: 8, borderColor: colors.teal, backgroundColor: '#F0FCF9', alignItems: 'center', justifyContent: 'center' },
  planProgressValue: { fontFamily: font, color: colors.text, fontSize: 18 },
  planProgressLabel: { fontFamily: font, color: colors.sub, fontSize: 11 },
  planPrimaryActions: { flexDirection: 'row', gap: 8, paddingHorizontal: 14, paddingBottom: 14 },
  planActionHero: { backgroundColor: '#FFFFFF', borderRadius: 12, borderWidth: 1, borderColor: colors.borderSoft, padding: 10, marginBottom: 10, ...shadow },
  planActionHeroCopy: { paddingRight: 104, minHeight: 92, justifyContent: 'center' },
  planActionVisual: { position: 'absolute', right: 14, top: 14, width: 90, height: 92, borderRadius: 12, overflow: 'hidden', borderWidth: 1, borderColor: '#FFE1B8', backgroundColor: '#FFF7ED' },
  planActionImage: { position: 'absolute', width: '100%', height: '100%', opacity: 0.86 },
  planActionOrb: { position: 'absolute', right: 8, bottom: 8, width: 54, height: 54, borderRadius: 27, backgroundColor: 'rgba(255,255,255,0.92)', borderWidth: 5, borderColor: colors.teal, alignItems: 'center', justifyContent: 'center' },
  planActionButtons: { flexDirection: 'row', gap: 8, marginTop: 12 },
  planCompactSummary: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  planCompactSummaryText: { flex: 1, fontFamily: font, color: colors.sub, fontSize: 12 },
  planSummaryStrip: { flexDirection: 'row', gap: 8, marginTop: 10 },
  planSummaryItem: { flex: 1, minHeight: 62, borderRadius: 10, borderWidth: 1, borderColor: '#D8E8FF', backgroundColor: '#F8FAFF', paddingHorizontal: 10, paddingVertical: 8, justifyContent: 'space-between' },
  planSummaryItemOrange: { backgroundColor: '#FFF8EE', borderColor: '#FFD9A6' },
  planSummaryItemTeal: { backgroundColor: '#F0FCF9', borderColor: '#BEEADF' },
  planSummaryValue: { fontFamily: font, color: colors.text, fontSize: 18 },
  planSummaryLabel: { fontFamily: font, color: colors.sub, fontSize: 11 },
  planStrip: { flexDirection: 'row', gap: 8, paddingRight: 12, marginBottom: 8 },
  planFocusRow: { flexDirection: 'row', gap: 10, marginBottom: 4 },
  planFocusTile: { flex: 1, backgroundColor: '#F0F6FF', borderWidth: 1, borderColor: '#D8E8FF', borderRadius: 10, padding: 14 },
  planFocusTileTeal: { backgroundColor: '#EFFBFA', borderColor: '#CFF3EF' },
  planMiniTrack: { height: 6, borderRadius: 99, backgroundColor: '#D8E8FF', overflow: 'hidden', marginTop: 8 },
  planMiniFill: { height: 6, borderRadius: 99, backgroundColor: colors.primary },
  planSubjectStrip: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 8 },
  planSubjectChip: { minWidth: '23%', flexGrow: 1, borderRadius: 10, borderWidth: 1, padding: 10 },
  planQueuePanel: { backgroundColor: '#FFFDF8', borderRadius: 12, borderWidth: 1, borderColor: '#EAE2D2', padding: 12, marginBottom: 10, ...shadow },
  planTodayDock: { backgroundColor: '#FFFFFF', borderRadius: 12, borderWidth: 1, borderColor: colors.borderSoft, padding: 12, marginBottom: 10, ...shadow },
  planQueueEmpty: { backgroundColor: '#FFFFFF', borderRadius: 10, borderWidth: 1, borderColor: colors.borderSoft, padding: 12 },
  planQueueList: { gap: 8 },
  planQueueItem: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#FFFFFF', borderRadius: 10, borderWidth: 1, borderLeftWidth: 4, borderColor: colors.borderSoft, padding: 10 },
  planQueueItemCurrent: { backgroundColor: '#FFF8EE', borderColor: '#FFD9A6' },
  planQueueItemDone: { backgroundColor: '#F0FCF9', borderColor: '#BEEADF', opacity: 0.76 },
  planQueueIndex: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  planQueueIndexText: { fontFamily: font, color: '#FFFFFF', fontSize: 12 },
  planMoreTasksLink: { alignSelf: 'flex-start', minHeight: 32, borderRadius: 8, backgroundColor: '#F8FAFF', borderWidth: 1, borderColor: '#D8E8FF', paddingHorizontal: 10, paddingVertical: 7, marginTop: 2 },
  planMoreTasksText: { fontFamily: font, color: colors.primaryDark, fontSize: 12 },
  planNowCard: { backgroundColor: '#FFFFFF', borderRadius: 12, borderWidth: 1, borderLeftWidth: 4, borderColor: colors.borderSoft, padding: 14, marginBottom: 10, ...shadow },
  planNowHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12, marginBottom: 8 },
  planNowTitle: { fontFamily: font, color: colors.text, fontSize: 18, lineHeight: 25, marginTop: -2 },
  planNowFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginTop: 12 },
  planNowActionGroup: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  planNowStartButton: { minHeight: 38, borderRadius: 9, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center' },
  planNowDoneButton: { backgroundColor: colors.primary, borderRadius: 8, paddingHorizontal: 14, paddingVertical: 9 },
  planNowDoneText: { fontFamily: font, color: '#FFFFFF', fontSize: 12 },
  planNowCheckButton: { minHeight: 38, borderRadius: 9, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: colors.borderSoft, paddingHorizontal: 11, alignItems: 'center', justifyContent: 'center' },
  planNowCheckText: { fontFamily: font, color: colors.sub, fontSize: 12 },
  planToolsBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginTop: 10, marginBottom: 4 },
  planRhythmPanel: { backgroundColor: '#FFFFFF', borderRadius: 12, borderWidth: 1, borderColor: colors.borderSoft, padding: 14, marginBottom: 10, ...shadow },
  planSubjectCards: { flexDirection: 'row', gap: 8, marginTop: 12 },
  planSubjectCard: { flex: 1, minHeight: 96, borderRadius: 10, borderWidth: 1, padding: 10, justifyContent: 'space-between' },
  planSubjectName: { fontFamily: font, fontSize: 12 },
  planSubjectCount: { fontFamily: font, color: colors.text, fontSize: 20 },
  planBoardToggle: { backgroundColor: colors.chip, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8 },
  planBoardToggleText: { fontFamily: font, color: colors.primaryDark, fontSize: 12 },
  planGeneratedCard: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#F0FCF9', borderRadius: 10, borderWidth: 1, borderColor: '#BCEDE7', padding: 12, marginBottom: 12 },
  planGeneratedIcon: { width: 34, height: 34, borderRadius: 17, backgroundColor: colors.teal, alignItems: 'center', justifyContent: 'center' },
  planGeneratedIconText: { fontFamily: font, color: '#FFFFFF', fontSize: 18 },
  planGeneratedAction: { borderRadius: 8, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#BCEDE7', paddingHorizontal: 10, paddingVertical: 8 },
  planGeneratedActionText: { fontFamily: font, color: '#087C72', fontSize: 12 },
  planTimeline: { backgroundColor: '#FFFFFF', borderRadius: 12, borderWidth: 1, borderColor: colors.borderSoft, padding: 12, marginBottom: 10, ...shadow },
  planTimelineItem: { flexDirection: 'row', alignItems: 'stretch', gap: 10 },
  planTimelineRail: { width: 30, alignItems: 'center' },
  planTimelineDot: { width: 28, height: 28, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  planTimelineDotText: { fontFamily: font, color: '#FFFFFF', fontSize: 12 },
  planTimelineLine: { flex: 1, width: 2, backgroundColor: colors.borderSoft, marginVertical: 4 },
  planTaskRow: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#FAFBFC', borderRadius: 10, borderWidth: 1, borderColor: colors.borderSoft, padding: 12, marginBottom: 10 },
  planTaskRowDone: { opacity: 0.66, backgroundColor: '#FAFBFC' },
  planTaskSubjectMark: { width: 4, alignSelf: 'stretch', borderRadius: 99 },
  planTaskTitleDone: { textDecorationLine: 'line-through', color: colors.sub },
  planTaskTime: { fontFamily: font, color: colors.muted, fontSize: 11 },
  planTaskMetaLine: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 4 },
  planTaskCheck: { width: 26, height: 26, borderRadius: 13, borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center' },
  planTaskCheckDone: { backgroundColor: colors.teal, borderColor: colors.teal },
  planTaskCheckText: { fontFamily: font, color: colors.muted, fontSize: 15 },
  planTaskCheckTextDone: { color: '#FFFFFF' },
  planDay: { width: 96, minHeight: 82, borderRadius: 10, borderWidth: 1, borderColor: colors.borderSoft, backgroundColor: '#FFFFFF', paddingVertical: 10, paddingHorizontal: 10, justifyContent: 'space-between' },
  planDayActive: { backgroundColor: '#EEF6FF', borderColor: '#BFD8FF', borderBottomWidth: 3, borderBottomColor: colors.primary },
  planDayLabel: { fontFamily: font, color: colors.sub, fontSize: 11 },
  planDayLabelActive: { color: colors.primaryDark },
  planDayDate: { fontFamily: font, color: colors.text, fontSize: 12 },
  planDayDateActive: { color: colors.primaryDark },
  planDayCount: { fontFamily: font, color: colors.muted, fontSize: 11 },
  planDayCountActive: { color: colors.primaryDark },
  planDayTrack: { height: 5, borderRadius: 99, backgroundColor: '#EDF1F7', overflow: 'hidden', marginTop: 8 },
  planDayFill: { height: 5, borderRadius: 99, backgroundColor: colors.teal },
  accountHero: { minHeight: 88, backgroundColor: colors.card, borderRadius: 12, padding: 12, borderWidth: 1, borderColor: colors.borderSoft, marginTop: 10, marginBottom: 8, flexDirection: 'row', alignItems: 'center', gap: 9, overflow: 'hidden', ...shadow },
  accountHeroImage: { position: 'absolute', right: 0, top: 0, width: '42%', height: 88, opacity: 0.42, backgroundColor: colors.panel },
  accountAvatar: { width: 40, height: 40, borderRadius: 10, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: '#D8E8FF', ...shadow },
  accountAvatarText: { fontFamily: font, color: colors.primaryDark, fontSize: 18 },
  myCommandCard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#FFFDF8', borderRadius: 12, borderWidth: 1, borderColor: '#EAE2D2', padding: 12, marginBottom: 8, ...shadow },
  myCommandActions: { flexDirection: 'row', gap: 8, marginTop: 10 },
  myCommandAction: { minHeight: 34, borderRadius: 8, backgroundColor: colors.primary, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center' },
  myCommandActionHot: { minHeight: 34, borderRadius: 8, backgroundColor: colors.orange, paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center' },
  myCommandActionText: { fontFamily: font, color: '#FFFFFF', fontSize: 12 },
  myCommandActionHotText: { fontFamily: font, color: '#FFFFFF', fontSize: 12 },
  myCommandActionMuted: { minHeight: 34, borderRadius: 8, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#EAE2D2', paddingHorizontal: 12, alignItems: 'center', justifyContent: 'center' },
  myCommandActionMutedText: { fontFamily: font, color: colors.sub, fontSize: 12 },
  myCommandMeter: { width: 62, height: 62, borderRadius: 31, borderWidth: 7, borderColor: colors.orange, backgroundColor: '#FFF7ED', alignItems: 'center', justifyContent: 'center' },
  myCommandMeterValue: { fontFamily: font, color: colors.text, fontSize: 16 },
  myCommandMeterLabel: { fontFamily: font, color: colors.sub, fontSize: 11 },
  mineStatsGrid: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  mineStatCard: { flex: 1, minHeight: 104, backgroundColor: '#F0F6FF', borderRadius: 10, borderWidth: 1, borderColor: '#D8E8FF', padding: 12, justifyContent: 'space-between' },
  mineStatCardTeal: { backgroundColor: '#EFFBFA', borderColor: '#CFF3EF' },
  mineStatCardOrange: { backgroundColor: '#FFF7ED', borderColor: '#FFE1B8' },
  myQuickPanel: { backgroundColor: '#FFFFFF', borderRadius: 12, borderWidth: 1, borderColor: colors.borderSoft, padding: 12, marginBottom: 10, ...shadow },
  myQuickGrid: { flexDirection: 'row', gap: 8, marginTop: 8, marginBottom: 8 },
  myQuickButton: { flex: 1, minHeight: 58, backgroundColor: '#F0F6FF', borderRadius: 10, borderWidth: 1, borderColor: '#D8E8FF', padding: 8, justifyContent: 'space-between' },
  myQuickButtonTeal: { backgroundColor: '#EFFBFA', borderColor: '#CFF3EF' },
  myQuickButtonOrange: { backgroundColor: '#FFF7ED', borderColor: '#FFE1B8' },
  myQuickValue: { fontFamily: font, color: colors.text, fontSize: 18 },
  myQuickTitle: { fontFamily: font, color: colors.text, fontSize: 12 },
  myQuickSub: { fontFamily: font, color: colors.sub, fontSize: 10 },
  myProgressBand: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#FAFBFC', borderRadius: 10, borderWidth: 1, borderColor: colors.borderSoft, paddingHorizontal: 9, paddingVertical: 7 },
  myProgressTrack: { height: 6, borderRadius: 99, backgroundColor: '#EDF1F7', overflow: 'hidden', marginTop: 7 },
  myProgressFill: { height: 6, borderRadius: 99, backgroundColor: colors.teal },
  myProgressValue: { fontFamily: font, color: '#087A7D', fontSize: 18 },
  myJourneyCard: { backgroundColor: '#FFFFFF', borderRadius: 12, borderWidth: 1, borderColor: colors.borderSoft, padding: 12, marginBottom: 10, ...shadow },
  myJourneyImage: { width: '100%', height: 104, borderRadius: 10, backgroundColor: colors.panel, marginBottom: 12 },
  myJourneyCompactHero: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#F8FAFF', borderRadius: 10, borderWidth: 1, borderColor: '#E6EEFF', padding: 8, marginTop: 10 },
  myJourneyCompactImage: { width: 72, height: 52, borderRadius: 8, backgroundColor: colors.panel },
  myJourneyCompactCopy: { flex: 1 },
  myJourneyCompactTitle: { fontFamily: font, color: colors.text, fontSize: 14, marginBottom: 2 },
  myJourneySteps: { flexDirection: 'row', alignItems: 'center', marginTop: 12 },
  myJourneyStep: { width: 54, alignItems: 'center' },
  myJourneyDot: { width: 12, height: 12, borderRadius: 6, marginBottom: 7 },
  myJourneyDotBlue: { backgroundColor: colors.primary },
  myJourneyDotTeal: { backgroundColor: colors.teal },
  myJourneyDotOrange: { backgroundColor: colors.orange },
  myJourneyDotGray: { backgroundColor: colors.muted },
  myJourneyLine: { flex: 1, height: 2, borderRadius: 99, backgroundColor: colors.borderSoft, marginBottom: 28 },
  myJourneyValue: { fontFamily: font, color: colors.text, fontSize: 18 },
  myJourneyLabel: { fontFamily: font, color: colors.sub, fontSize: 11, marginTop: 2 },
  myFlowStrip: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#FFFFFF', borderRadius: 12, borderWidth: 1, borderColor: colors.borderSoft, padding: 10, marginBottom: 10, ...shadow },
  myFlowStripImage: { width: 54, height: 54, borderRadius: 8, backgroundColor: '#E8EEF8' },
  myFlowStripBody: { flex: 1, minWidth: 0 },
  myShortcutPanel: { backgroundColor: '#FFFFFF', borderRadius: 12, borderWidth: 1, borderColor: colors.borderSoft, padding: 12, marginBottom: 10, ...shadow },
  myShortcutRail: { flexDirection: 'row', gap: 8, paddingTop: 8, paddingRight: 12 },
  myShortcut: { width: 118, minHeight: 72, borderRadius: 10, borderWidth: 1, padding: 10, justifyContent: 'space-between' },
  myShortcut_blue: { backgroundColor: '#F0F6FF', borderColor: '#D8E8FF' },
  myShortcut_teal: { backgroundColor: '#EFFBFA', borderColor: '#CFF3EF' },
  myShortcut_orange: { backgroundColor: '#FFF7ED', borderColor: '#FFE1B8' },
  myShortcut_gray: { backgroundColor: '#F6F7F9', borderColor: '#E8EAED' },
  myShortcutTitle: { fontFamily: font, color: colors.text, fontSize: 14 },
  myShortcutSub: { fontFamily: font, color: colors.sub, fontSize: 11 },
  profileSummary: { backgroundColor: '#F8FAFF', borderRadius: 8, padding: 12, borderWidth: 1, borderColor: '#E6EEFF', marginBottom: 10 },
  mySectionPanel: { backgroundColor: '#FFFFFF', borderRadius: 12, borderWidth: 1, borderColor: colors.borderSoft, padding: 14, marginBottom: 10, ...shadow },
  myMorePanel: { backgroundColor: '#FFFFFF', borderRadius: 12, borderWidth: 1, borderColor: colors.borderSoft, padding: 14, marginBottom: 10, ...shadow },
  myMoreHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  myMoreToggle: { fontFamily: font, color: colors.primaryDark, fontSize: 12, backgroundColor: colors.chip, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, overflow: 'hidden' },
  settingsList: { backgroundColor: colors.card, borderRadius: 8, borderWidth: 1, borderColor: colors.borderSoft, padding: 12, marginBottom: 10, borderLeftWidth: 4, borderLeftColor: colors.teal, ...shadow },
  settingsRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.borderSoft },
  settingsIcon: { width: 34, height: 34, borderRadius: 8, backgroundColor: '#EEF6FF', alignItems: 'center', justifyContent: 'center' },
  settingsIconTeal: { backgroundColor: '#E9FBF8' },
  settingsIconText: { fontFamily: font, color: colors.primaryDark, fontSize: 14 },
  entitlementBanner: { backgroundColor: colors.card, borderRadius: 10, borderWidth: 1, borderColor: colors.borderSoft, padding: 14, marginBottom: 10, borderLeftWidth: 4, borderLeftColor: colors.teal, ...shadow },
  decisionPreview: { backgroundColor: colors.card, borderRadius: 10, borderWidth: 1, borderColor: colors.borderSoft, padding: 14, marginBottom: 10, ...shadow },
  decisionPreviewNested: { backgroundColor: '#FAFBFC', borderRadius: 10, borderWidth: 1, borderColor: colors.borderSoft, padding: 12, marginTop: 12 },
  myDecisionActions: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  myDecisionToggle: { backgroundColor: colors.chip, borderRadius: 8, paddingHorizontal: 12, paddingVertical: 9 },
  myDecisionToggleText: { fontFamily: font, color: colors.primaryDark, fontSize: 12 },
  myDecisionSummary: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#FFF8EE', borderRadius: 10, borderWidth: 1, borderColor: '#FFD9A6', padding: 12, marginTop: 12 },
  decisionRail: { gap: 10, paddingTop: 8, paddingBottom: 4 },
  decisionRailCard: { width: 184, minHeight: 190, backgroundColor: '#FFFFFF', borderRadius: 10, borderWidth: 1, borderTopWidth: 4, borderColor: colors.borderSoft, padding: 12 },
  decisionScoreRow: { flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', gap: 8, marginTop: 8, marginBottom: 8 },
  decisionDeleteButton: { alignSelf: 'flex-start', marginTop: 'auto', paddingTop: 8 },
  todayHero: { backgroundColor: colors.card, borderRadius: 10, padding: 12, borderWidth: 1, borderColor: colors.borderSoft, marginTop: 10, marginBottom: 10, ...shadow },
  todayHeroImage: { width: '100%', height: 98, borderRadius: 10, marginBottom: 10, backgroundColor: colors.panel },
  todayHeroMain: { flexDirection: 'row', alignItems: 'flex-end', gap: 12 },
  todayHeroCopy: { flex: 1 },
  todayHeroTitle: { fontFamily: brandFont, color: colors.text, fontSize: 20, lineHeight: 26, marginBottom: 3 },
  todayProgressDial: { width: 90, height: 90, borderRadius: 45, borderWidth: 9, backgroundColor: '#FFFFFF', alignItems: 'center', justifyContent: 'center' },
  todayProgressValue: { fontFamily: font, color: colors.text, fontSize: 20 },
  todayProgressLabel: { fontFamily: font, color: colors.sub, fontSize: 11 },
  todayHeroStats: { flexDirection: 'row', gap: 8, marginTop: 14 },
  todayHeroStat: { flex: 1, backgroundColor: '#F8FAFF', borderRadius: 8, borderWidth: 1, borderColor: '#E6EEFF', padding: 10 },
  todayHeroMeta: { flexDirection: 'row', alignItems: 'center', gap: 8, flexWrap: 'wrap', marginTop: 7 },
  todayPrimaryAction: { minWidth: 92, minHeight: 40, borderRadius: 9, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
  todayPrimaryActionText: { fontFamily: font, color: '#FFFFFF', fontSize: 13 },
  todayChipRail: { flexDirection: 'row', gap: 7, marginTop: 9, marginBottom: 8 },
  todayStatChip: { flex: 1, minHeight: 38, borderRadius: 9, borderWidth: 1, borderColor: '#D8E8FF', backgroundColor: '#F8FAFF', paddingHorizontal: 9, paddingVertical: 5, justifyContent: 'center' },
  todayStatChipTeal: { backgroundColor: '#F0FCF9', borderColor: '#BEEADF' },
  todayStatChipOrange: { backgroundColor: '#FFF7ED', borderColor: '#FFE1B8' },
  todayStatChipValue: { fontFamily: font, color: colors.primaryDark, fontSize: 16, marginBottom: 1 },
  todayStatChipLabel: { fontFamily: font, color: colors.sub, fontSize: 10 },
  todayActionDock: { flexDirection: 'row', gap: 8, marginTop: 14, marginBottom: 12 },
  todayActionButton: { flex: 1, minHeight: 82, backgroundColor: '#F8FAFF', borderRadius: 10, borderWidth: 1, borderColor: '#D8E8FF', padding: 10, justifyContent: 'space-between' },
  todayActionButtonHot: { backgroundColor: '#FFF7ED', borderColor: '#FFE1B8' },
  todayActionButtonDone: { backgroundColor: '#F0FCF9', borderColor: '#BEEADF' },
  todayActionValue: { fontFamily: font, color: colors.primaryDark, fontSize: 20 },
  todayActionTitle: { fontFamily: font, color: colors.text, fontSize: 12 },
  todayActionSub: { fontFamily: font, color: colors.sub, fontSize: 10 },
  todayDoneCard: { backgroundColor: '#F0FCF9', borderRadius: 10, borderWidth: 1, borderColor: '#BEEADF', padding: 14, marginBottom: 10 },
  workflowGrid: { flexDirection: 'row', gap: 8, marginBottom: 8 },
  workflowCard: { flex: 1, minHeight: 108, backgroundColor: colors.card, borderRadius: 8, borderWidth: 1, borderColor: colors.borderSoft, borderTopWidth: 3, padding: 10, justifyContent: 'space-between', ...shadow },
  workflowValue: { fontFamily: font, color: colors.text, fontSize: 20 },
  workflowLabel: { fontFamily: font, color: colors.text, fontSize: 12 },
  workflowDetail: { fontFamily: font, color: colors.sub, fontSize: 11 },
  todayFlowBand: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FAFBFC', borderRadius: 10, borderWidth: 1, borderColor: colors.borderSoft, padding: 8, marginBottom: 2 },
  todayFlowStep: { flex: 1, minHeight: 78, alignItems: 'center', justifyContent: 'center', paddingVertical: 4 },
  todayFlowIndex: { width: 24, height: 24, borderRadius: 12, alignItems: 'center', justifyContent: 'center', marginBottom: 5 },
  todayFlowIndexText: { fontFamily: font, color: '#FFFFFF', fontSize: 11 },
  todayFlowValue: { fontFamily: font, color: colors.text, fontSize: 18, marginVertical: 1 },
  todayFlowConnector: { width: 16, height: 2, backgroundColor: colors.borderSoft, alignSelf: 'center', marginHorizontal: 0 },
  collapsibleHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  collapsibleBody: { marginTop: 10, paddingTop: 10, borderTopWidth: 1, borderTopColor: colors.borderSoft },
  disclosure: { fontFamily: font, color: colors.primaryDark, fontSize: 12 },
  segment: { flexDirection: 'row', gap: 6, backgroundColor: '#F2F3F5', borderRadius: 8, padding: 4, marginTop: 18 },
  segmentItem: { flex: 1, borderRadius: 6, paddingVertical: 8, alignItems: 'center' },
  segmentItemActive: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: colors.borderSoft },
  segmentText: { fontFamily: font, color: colors.sub, fontSize: 12 },
  segmentTextActive: { color: colors.primaryDark },
  emptyState: { alignItems: 'center', justifyContent: 'center', backgroundColor: colors.card, borderRadius: 8, borderWidth: 1, borderColor: colors.borderSoft, padding: 18, marginBottom: 10 },
  emptyImage: { width: 190, height: 130, marginBottom: 8 },
  statusPill: { borderRadius: 6, paddingHorizontal: 8, paddingVertical: 4, alignSelf: 'flex-start' },
  statusPill_blue: { backgroundColor: '#EAF2FF' },
  statusPill_teal: { backgroundColor: '#E9FBF8' },
  statusPill_orange: { backgroundColor: '#FFF3E0' },
  statusPill_red: { backgroundColor: '#FFF0F0' },
  statusPill_gray: { backgroundColor: '#F2F3F5' },
  statusPillText: { fontFamily: font, fontSize: 11 },
  statusPillText_blue: { color: colors.primaryDark },
  statusPillText_teal: { color: '#08979C' },
  statusPillText_orange: { color: '#B95E00' },
  statusPillText_red: { color: colors.red },
  statusPillText_gray: { color: colors.sub },
  taskCheck: { fontFamily: font, fontSize: 20, color: colors.primaryDark, paddingLeft: 8 },
  taskCard: { borderLeftWidth: 4 },
  taskMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 6 },
  listItem: { paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.borderSoft },
  importGroupLabel: { fontFamily: font, color: colors.sub, fontSize: 12, marginTop: 8, marginBottom: 8 },
  importOption: { borderWidth: 1, borderColor: colors.borderSoft, borderRadius: 8, padding: 12, backgroundColor: '#fff', marginBottom: 8 },
  importOptionRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  importFileIcon: { fontFamily: font, width: 42, height: 42, borderRadius: 10, backgroundColor: '#F2F6FF', color: colors.primaryDark, textAlign: 'center', lineHeight: 42, fontSize: 12, overflow: 'hidden' },
  importOptionDisabled: { backgroundColor: '#F6F7F9', opacity: 0.72 },
  importHero: { backgroundColor: colors.panel, borderRadius: 8, padding: 12, borderWidth: 1, borderColor: '#D8E8FF', marginBottom: 10 },
  importSuccess: { backgroundColor: '#E9FBF8', borderRadius: 8, padding: 12, borderWidth: 1, borderColor: '#CFF3EF', marginBottom: 10, flexDirection: 'row', alignItems: 'center', gap: 10 },
  importSuccessCard: { backgroundColor: '#F0FCF9', borderRadius: 12, padding: 14, borderWidth: 1, borderTopWidth: 4, borderColor: '#BEEADF', borderTopColor: colors.teal, marginBottom: 12, gap: 10, ...shadow },
  importSuccessHeader: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  importSuccessIcon: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  importSuccessIconText: { fontFamily: font, color: '#FFFFFF', fontSize: 22 },
  importSuccessDoc: { width: 64, height: 78, borderRadius: 10, borderWidth: 1, alignItems: 'center', justifyContent: 'center', backgroundColor: '#FFFFFF', ...shadow },
  importSuccessDocCover: { width: 66, height: 82, borderRadius: 11, borderWidth: 1, overflow: 'hidden', alignItems: 'flex-end', justifyContent: 'flex-end', backgroundColor: colors.panel, ...shadow },
  importSuccessDocCoverImage: { borderRadius: 11 },
  importSuccessDocType: { fontFamily: font, fontSize: 16, marginBottom: 8, opacity: 0.42 },
  importSuccessDocLine: { width: 38, height: 4, borderRadius: 99, backgroundColor: '#DADDE3', marginBottom: 7 },
  importSuccessDocBadge: { position: 'absolute', left: 7, bottom: 7, color: '#FFFFFF', fontFamily: font, fontSize: 9, paddingHorizontal: 5, paddingVertical: 2, borderRadius: 4, overflow: 'hidden' },
  importSuccessCoach: { flexDirection: 'row', alignItems: 'center', gap: 9, backgroundColor: '#FFFFFF', borderRadius: 10, borderWidth: 1, borderColor: '#BEEADF', paddingHorizontal: 10, paddingVertical: 9 },
  importSuccessCoachDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.teal },
  importSuccessCoachTitle: { fontFamily: font, color: '#087A7D', fontSize: 13, marginBottom: 2 },
  importSuccessCoachText: { fontFamily: font, color: colors.sub, fontSize: 11, lineHeight: 17 },
  importSuccessActions: { gap: 8 },
  importSuccessActionRow: { flexDirection: 'row', gap: 8 },
  importSuccessProgress: { flexDirection: 'row', alignItems: 'center', marginTop: 10 },
  importSuccessStepDone: { backgroundColor: '#DDF8F3', borderRadius: 99, paddingHorizontal: 8, paddingVertical: 4 },
  importSuccessStepNow: { backgroundColor: '#FFF8EE', borderRadius: 99, borderWidth: 1, borderColor: '#FFD9A6', paddingHorizontal: 8, paddingVertical: 4 },
  importSuccessStepTextDone: { fontFamily: font, color: '#087A7D', fontSize: 11 },
  importSuccessStepTextNow: { fontFamily: font, color: '#B95E00', fontSize: 11 },
  importSuccessLine: { width: 18, height: 1, backgroundColor: '#BEEADF', marginHorizontal: 4 },
  importSuccessMetaRow: { flexDirection: 'row', gap: 8 },
  importSuccessMeta: { flex: 1, backgroundColor: '#FFFFFF', borderRadius: 8, borderWidth: 1, borderColor: '#CFF3EF', padding: 10 },
  importSuccessStatusGrid: { flexDirection: 'row', gap: 8 },
  importSuccessStatusItem: { flex: 1, backgroundColor: '#FFFFFF', borderRadius: 10, borderWidth: 1, borderColor: '#CFF3EF', padding: 10 },
  importSuccessStatusItemHot: { flex: 1, backgroundColor: '#FFF8EE', borderRadius: 10, borderWidth: 1, borderColor: '#FFD9A6', padding: 10 },
  importSuccessStatusValue: { fontFamily: font, color: '#087A7D', fontSize: 17, marginBottom: 2 },
  importSuccessStatusValueHot: { fontFamily: font, color: '#B95E00', fontSize: 17, marginBottom: 2 },
  importSuccessStatusLabel: { fontFamily: font, color: colors.sub, fontSize: 11 },
  importCommand: { backgroundColor: colors.card, borderRadius: 8, padding: 14, borderWidth: 1, borderColor: colors.borderSoft, marginTop: 14, marginBottom: 18, flexDirection: 'row', alignItems: 'center', gap: 12, ...shadow },
  materialHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, marginBottom: 12 },
  materialHeaderActions: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  materialHeaderImportButton: { minWidth: 58, height: 40, borderRadius: 11, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12, ...shadow },
  materialHeaderImportText: { fontFamily: font, color: '#FFFFFF', fontSize: 13 },
  headerIconButton: { width: 40, height: 40, borderRadius: 11, backgroundColor: colors.card, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.borderSoft, ...shadow },
  headerIconButtonText: { fontFamily: font, color: colors.text, fontSize: 24, lineHeight: 28 },
  layoutGlyphList: { width: 22, height: 18, justifyContent: 'space-between' },
  layoutGlyphLine: { height: 3, borderRadius: 99, backgroundColor: colors.text },
  layoutGlyphGrid: { width: 22, height: 22, flexDirection: 'row', flexWrap: 'wrap', gap: 4 },
  layoutGlyphCell: { width: 9, height: 9, borderRadius: 3, borderWidth: 2, borderColor: colors.text },
  plusGlyph: { width: 24, height: 24, alignItems: 'center', justifyContent: 'center' },
  plusGlyphVertical: { position: 'absolute', width: 3, height: 22, borderRadius: 99, backgroundColor: colors.primaryDark },
  plusGlyphHorizontal: { position: 'absolute', width: 22, height: 3, borderRadius: 99, backgroundColor: colors.primaryDark },
  plusGlyphVerticalLight: { position: 'absolute', width: 3, height: 22, borderRadius: 99, backgroundColor: '#FFFFFF' },
  plusGlyphHorizontalLight: { position: 'absolute', width: 22, height: 3, borderRadius: 99, backgroundColor: '#FFFFFF' },
  libraryHero: { backgroundColor: colors.card, borderRadius: 10, padding: 16, borderWidth: 1, borderColor: colors.borderSoft, marginTop: 14, marginBottom: 18, flexDirection: 'row', alignItems: 'center', gap: 12, ...shadow },
  libraryHeroImage: { width: 88, height: 68, borderRadius: 8, backgroundColor: colors.panel },
  libraryPipeline: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FFFFFF', borderRadius: 8, borderWidth: 1, borderColor: colors.borderSoft, padding: 10, marginBottom: 6 },
  pipelineMiniStep: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  pipelineMiniIndex: { fontFamily: font, width: 18, height: 18, borderRadius: 9, backgroundColor: colors.chip, color: colors.primaryDark, textAlign: 'center', lineHeight: 18, fontSize: 11 },
  pipelineMiniText: { fontFamily: font, color: colors.sub, fontSize: 11 },
  pipelineMiniLine: { flex: 1, height: 1, backgroundColor: colors.borderSoft, marginHorizontal: 6 },
  libraryTabs: { flexDirection: 'row', gap: 7, paddingRight: 12, marginBottom: 8 },
  libraryTab: { paddingHorizontal: 9, paddingVertical: 6, backgroundColor: '#F2F3F5', borderRadius: 8, borderWidth: 1, borderColor: colors.borderSoft },
  libraryTabActive: { backgroundColor: colors.chip },
  libraryTabText: { fontFamily: font, color: colors.sub, fontSize: 12 },
  libraryTabTextActive: { color: colors.primaryDark },
  librarySignalRail: { flexDirection: 'row', gap: 8, paddingRight: 12, marginBottom: 12 },
  librarySignalCard: { width: 108, minHeight: 78, borderRadius: 10, borderWidth: 1, borderColor: '#D8E8FF', backgroundColor: '#F8FAFF', padding: 10, justifyContent: 'space-between' },
  librarySignalCardHot: { backgroundColor: '#FFF8EE', borderColor: '#FFD9A6' },
  librarySignalCardTeal: { backgroundColor: '#F0FCF9', borderColor: '#BEEADF' },
  librarySignalCardDisabled: { opacity: 0.58 },
  librarySignalLabel: { fontFamily: font, color: colors.primaryDark, fontSize: 10, marginBottom: 2 },
  librarySignalLabelHot: { fontFamily: font, color: '#B95E00', fontSize: 10, marginBottom: 2 },
  librarySignalLabelTeal: { fontFamily: font, color: '#087A7D', fontSize: 10, marginBottom: 2 },
  librarySignalValue: { fontFamily: font, color: colors.text, fontSize: 13 },
  librarySignalValueHot: { fontFamily: font, color: '#B95E00', fontSize: 15 },
  librarySignalValueTeal: { fontFamily: font, color: '#087A7D', fontSize: 15 },
  librarySignalAction: { fontFamily: font, color: colors.sub, fontSize: 10 },
  librarySignalActionHot: { fontFamily: font, color: '#B95E00', fontSize: 10 },
  librarySignalActionTeal: { fontFamily: font, color: '#087A7D', fontSize: 10 },
  libraryStatusStrip: { flexDirection: 'row', gap: 6, marginBottom: 6 },
  libraryStatusItem: { flex: 1, minHeight: 34, borderRadius: 8, borderWidth: 1, borderColor: '#D8E8FF', backgroundColor: '#F8FAFF', paddingHorizontal: 8, paddingVertical: 5, justifyContent: 'center' },
  libraryStatusItemHot: { backgroundColor: '#FFF8EE', borderColor: '#FFD9A6' },
  libraryStatusItemTeal: { backgroundColor: '#F0FCF9', borderColor: '#BEEADF' },
  librarySectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10, marginTop: 0, marginBottom: 8 },
  librarySectionTitle: { fontFamily: font, color: colors.text, fontSize: 16 },
  librarySectionHint: { fontFamily: font, color: colors.sub, fontSize: 11, marginTop: 2 },
  libraryHeaderAction: { minHeight: 32, borderRadius: 9, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 12 },
  libraryHeaderActionText: { fontFamily: font, color: '#FFFFFF', fontSize: 12 },
  materialList: { gap: 10, paddingBottom: 20 },
  materialListItem: { backgroundColor: colors.card, borderRadius: 10, borderWidth: 1, borderColor: colors.borderSoft, padding: 12, flexDirection: 'row', gap: 10, alignItems: 'flex-start', ...shadow },
  materialListItemNew: { backgroundColor: '#F0FCF9', borderColor: '#7EDFD2', borderWidth: 2 },
  materialListThumb: { width: 54, height: 64, borderRadius: 8, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  materialListThumbText: { fontFamily: font, fontSize: 13 },
  materialProgressRowCompact: { flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 7 },
  materialListActions: { width: 64, gap: 8 },
  materialListActionButton: { backgroundColor: colors.chip, borderRadius: 8, paddingVertical: 7, alignItems: 'center' },
  materialListActionButtonMuted: { backgroundColor: '#F6F7F9', borderRadius: 8, paddingVertical: 7, alignItems: 'center', borderWidth: 1, borderColor: colors.borderSoft },
  materialGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, paddingBottom: 150 },
  materialDocCard: { width: '48%', minHeight: 278, backgroundColor: colors.card, borderRadius: 12, padding: 0, borderWidth: 1, borderColor: colors.borderSoft, overflow: 'hidden', ...shadow },
  materialDocCardNew: { backgroundColor: '#F0FCF9', borderColor: '#7EDFD2', borderWidth: 2 },
  materialDocCardArchived: { opacity: 0.68, borderTopColor: colors.muted, backgroundColor: '#FAFBFC' },
  materialDocArt: { height: 128, backgroundColor: '#FAFBFC', borderBottomWidth: 1, borderBottomColor: colors.borderSoft, alignItems: 'center', justifyContent: 'center', padding: 10, overflow: 'hidden' },
  materialDocArtifactWrap: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, alignItems: 'center', justifyContent: 'center' },
  materialDocArtifactBg: { position: 'absolute', left: 0, right: 0, top: -16, bottom: -16, width: '100%', height: 160, opacity: 0.42 },
  materialDocArtifactVeil: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, backgroundColor: 'rgba(255,255,255,0.76)' },
  materialDocMiniStatus: { position: 'absolute', left: 10, top: 10, zIndex: 2, borderRadius: 99, paddingHorizontal: 8, paddingVertical: 5 },
  materialDocMiniStatusBlue: { backgroundColor: '#EAF2FF' },
  materialDocMiniStatusTeal: { backgroundColor: '#DDF8F3' },
  materialDocMiniStatusOrange: { backgroundColor: '#FFF0D6' },
  materialDocMiniStatusGray: { backgroundColor: '#F2F3F5' },
  materialDocMiniStatusText: { fontFamily: font, color: colors.primaryDark, fontSize: 10 },
  materialDocMiniStatusTextTeal: { color: '#087A7D' },
  materialDocMiniStatusTextOrange: { color: '#B95E00' },
  materialDocMiniStatusTextGray: { color: colors.sub },
  materialPaperThumb: { width: 86, height: 104, borderRadius: 10, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E1E5EA', alignItems: 'center', justifyContent: 'center', ...shadow },
  materialPaperFold: { position: 'absolute', right: -1, top: -1, width: 25, height: 25, borderLeftWidth: 1, borderBottomWidth: 1, borderColor: '#E1E5EA', backgroundColor: '#F8FAFC', borderTopRightRadius: 10 },
  materialPaperSymbol: { fontFamily: font, color: '#C8CDD4', fontSize: 20, marginBottom: 10 },
  materialPaperLine: { width: 48, height: 4, borderRadius: 99, backgroundColor: '#DADDE3', marginBottom: 8 },
  materialPaperLineShort: { width: 34 },
  materialPaperBadge: { position: 'absolute', left: 13, bottom: 12, color: '#FFFFFF', fontFamily: font, fontSize: 10, paddingHorizontal: 6, paddingVertical: 3, borderRadius: 4, overflow: 'hidden' },
  materialCoverImage: { position: 'absolute', left: 0, right: 0, top: -18, bottom: -18, width: '100%', height: 154 },
  materialCoverVeil: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, backgroundColor: 'rgba(255,255,255,0.08)' },
  materialDocStatusFloating: { position: 'absolute', left: 10, top: 10, zIndex: 2 },
  materialDocIcon: { width: 62, height: 74, borderRadius: 10, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E1E5EA', alignItems: 'center', justifyContent: 'center', ...shadow },
  materialDocWatermark: { position: 'absolute', right: 12, bottom: 6, fontFamily: font, fontSize: 28, opacity: 0.12 },
  materialDocFold: { position: 'absolute', right: -1, top: -1, width: 22, height: 22, borderLeftWidth: 1, borderBottomWidth: 1, borderColor: '#E1E5EA', backgroundColor: '#F8FAFC', borderTopRightRadius: 8 },
  materialDocSymbol: { fontFamily: font, fontSize: 18, opacity: 0.2, marginBottom: 8 },
  materialDocLine: { width: 48, height: 4, borderRadius: 99, backgroundColor: '#DADDE3', marginBottom: 7 },
  materialDocBadge: { position: 'absolute', left: 10, bottom: 9, color: '#FFFFFF', fontFamily: font, fontSize: 10, paddingHorizontal: 6, paddingVertical: 3, borderRadius: 4, overflow: 'hidden' },
  materialCoverBadge: { position: 'absolute', right: 10, bottom: 10, minWidth: 38, height: 25, borderRadius: 7, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 8, ...shadow },
  materialCoverBadgeText: { fontFamily: font, color: '#FFFFFF', fontSize: 10 },
  materialNewRibbon: { position: 'absolute', right: 10, top: 10, backgroundColor: '#13A389', borderRadius: 99, paddingHorizontal: 8, paddingVertical: 4 },
  materialNewRibbonText: { fontFamily: font, color: '#FFFFFF', fontSize: 10 },
  materialDocBody: { paddingHorizontal: 10, paddingTop: 9, paddingBottom: 9 },
  materialDocTitleRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 6, marginBottom: 6 },
  materialDocTitle: { flex: 1, fontFamily: font, color: colors.text, fontSize: 14, lineHeight: 20 },
  materialMoreButton: { minWidth: 30, minHeight: 28, borderRadius: 8, backgroundColor: '#F6F7F9', borderWidth: 1, borderColor: colors.borderSoft, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6 },
  materialMoreText: { fontFamily: font, color: colors.text, fontSize: 14, lineHeight: 16 },
  materialMetaRow: { flexDirection: 'row', alignItems: 'center', gap: 7, marginBottom: 6 },
  materialCardCount: { fontFamily: font, color: colors.muted, fontSize: 12 },
  materialReviewRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 6 },
  materialClockGlyph: { width: 15, height: 15, borderRadius: 8, borderWidth: 1, borderColor: colors.muted, alignItems: 'center', justifyContent: 'center' },
  materialClockHand: { width: 5, height: 1, borderRadius: 99, backgroundColor: colors.muted, transform: [{ rotate: '35deg' }] },
  materialDocMeta: { fontFamily: font, color: colors.muted, fontSize: 11 },
  materialDocState: { fontFamily: font, color: colors.sub, fontSize: 11, lineHeight: 16, paddingHorizontal: 12, marginTop: 6 },
  materialDocState_blue: { color: colors.primaryDark },
  materialDocState_teal: { color: '#087A7D' },
  materialDocState_orange: { color: '#B95E00' },
  materialDocNext: { marginHorizontal: 10, marginTop: 7, marginBottom: 8, minHeight: 38, borderRadius: 9, borderWidth: 1, paddingHorizontal: 9, paddingVertical: 7, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 6 },
  materialDocNext_blue: { backgroundColor: '#F8FAFF', borderColor: '#D8E8FF' },
  materialDocNext_teal: { backgroundColor: '#F0FCF9', borderColor: '#BEEADF' },
  materialDocNext_orange: { backgroundColor: '#FFF8EE', borderColor: '#FFD9A6' },
  materialDocNextText: { fontFamily: font, fontSize: 12 },
  materialDocNextText_blue: { color: colors.primaryDark },
  materialDocNextText_teal: { color: '#087A7D' },
  materialDocNextText_orange: { color: '#B95E00' },
  materialDocNextSub: { flex: 1, fontFamily: font, color: colors.sub, fontSize: 10, textAlign: 'right' },
  materialProgressRow: { flexDirection: 'row', alignItems: 'center', gap: 7, paddingHorizontal: 10, marginTop: 6 },
  materialProgressTrack: { flex: 1, height: 5, borderRadius: 99, backgroundColor: '#EDF1F7', overflow: 'hidden' },
  materialProgressFill: { height: 5, borderRadius: 99 },
  materialProgressText: { fontFamily: font, color: colors.muted, fontSize: 10 },
  materialActionPreview: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#F8FAFF', borderRadius: 12, borderWidth: 1, borderColor: '#D8E8FF', padding: 12, marginBottom: 10 },
  materialDetailHero: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: '#FFFDF8', borderRadius: 12, borderWidth: 1, borderColor: '#EAE2D2', padding: 14, marginBottom: 10, ...shadow },
  materialDetailDoc: { width: 78, height: 96, borderRadius: 10, borderWidth: 1, alignItems: 'center', justifyContent: 'center' },
  materialDetailDocCover: { width: 86, height: 106, borderRadius: 12, borderWidth: 1, overflow: 'hidden', justifyContent: 'flex-end', alignItems: 'flex-end', backgroundColor: colors.panel },
  materialDetailDocCoverImage: { borderRadius: 12 },
  materialDetailHeroCopy: { flex: 1 },
  materialDetailHeroTitle: { fontFamily: brandFont, color: colors.text, fontSize: 20, lineHeight: 27, marginTop: 9, marginBottom: 5 },
  materialDetailHeroTrack: { height: 6, borderRadius: 99, backgroundColor: '#ECEFF3', overflow: 'hidden', marginTop: 10, marginBottom: 6 },
  materialDetailHeroFill: { height: 6, borderRadius: 99 },
  materialDetailStatsRow: { flexDirection: 'row', gap: 6, marginTop: 9 },
  materialDetailStat: { flex: 1, backgroundColor: 'rgba(255,255,255,0.72)', borderRadius: 8, borderWidth: 1, borderColor: colors.borderSoft, paddingHorizontal: 8, paddingVertical: 7 },
  materialDetailStatValue: { fontFamily: font, color: colors.text, fontSize: 16, marginBottom: 1 },
  materialDetailStatLabel: { fontFamily: font, color: colors.sub, fontSize: 10 },
  materialDetailCommand: { backgroundColor: '#F8FAFF', borderRadius: 12, borderWidth: 1, borderColor: '#D8E8FF', padding: 14, marginBottom: 10, flexDirection: 'row', alignItems: 'center', gap: 12 },
  materialDetailFlow: { backgroundColor: '#FAFBFC', borderRadius: 10, borderWidth: 1, borderColor: colors.borderSoft, padding: 12, marginBottom: 10 },
  materialDetailSourceCard: { backgroundColor: '#FAFBFC', borderRadius: 10, borderWidth: 1, borderColor: colors.borderSoft, padding: 12 },
  materialPipelineBadge: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, marginTop: 8 },
  materialPipelineStepDone: { backgroundColor: '#DDF8F3', borderRadius: 99, paddingHorizontal: 7, paddingVertical: 3 },
  materialPipelineStepIdle: { backgroundColor: '#F2F3F5', borderRadius: 99, paddingHorizontal: 7, paddingVertical: 3 },
  materialPipelineStepTextDone: { fontFamily: font, color: '#087A7D', fontSize: 10 },
  materialPipelineStepTextIdle: { fontFamily: font, color: colors.muted, fontSize: 10 },
  materialPipelineConnector: { flex: 1, minWidth: 7, height: 1, backgroundColor: colors.borderSoft },
  materialFreshFlow: { backgroundColor: '#F0FCF9', borderRadius: 9, borderWidth: 1, borderColor: '#BEEADF', padding: 8, marginTop: 8 },
  materialFreshFlowHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 7 },
  materialFreshFlowTitle: { fontFamily: font, color: '#087A7D', fontSize: 11 },
  materialFreshFlowCount: { fontFamily: font, color: '#087A7D', fontSize: 11 },
  materialFreshFlowSteps: { flexDirection: 'row', alignItems: 'center' },
  materialFreshStepDone: { backgroundColor: '#DDF8F3', borderRadius: 99, paddingHorizontal: 7, paddingVertical: 3 },
  materialFreshStepNow: { backgroundColor: '#FFF8EE', borderRadius: 99, paddingHorizontal: 7, paddingVertical: 3, borderWidth: 1, borderColor: '#FFD9A6' },
  materialFreshStepTextDone: { fontFamily: font, color: '#087A7D', fontSize: 10 },
  materialFreshStepTextNow: { fontFamily: font, color: '#B95E00', fontSize: 10 },
  materialFreshLine: { flex: 1, minWidth: 8, height: 1, backgroundColor: '#BEEADF' },
  materialFreshQueue: { flexDirection: 'row', alignItems: 'center', gap: 7, backgroundColor: '#FFFFFF', borderRadius: 8, borderWidth: 1, borderColor: '#BEEADF', paddingHorizontal: 8, paddingVertical: 7, marginTop: 8 },
  materialFreshQueueDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.teal },
  materialFreshQueueText: { flex: 1, fontFamily: font, color: '#087A7D', fontSize: 11 },
  materialFreshReviewButton: { minHeight: 34, borderRadius: 8, backgroundColor: colors.teal, alignItems: 'center', justifyContent: 'center', marginTop: 8 },
  materialFreshReviewText: { fontFamily: font, color: '#FFFFFF', fontSize: 12 },
  materialImportFab: { position: 'absolute', right: 20, bottom: 98, width: 78, height: 78, borderRadius: 39, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center', gap: 1, shadowColor: colors.primaryDark, shadowOpacity: 0.26, shadowRadius: 14, shadowOffset: { width: 0, height: 8 }, elevation: 5 },
  materialImportFabText: { fontFamily: font, color: '#FFFFFF', fontSize: 12 },
  materialQuickActions: { flexDirection: 'row', gap: 8, paddingHorizontal: 12, paddingBottom: 12, marginTop: 'auto' },
  materialQuickButton: { flex: 1, backgroundColor: colors.chip, borderRadius: 8, paddingVertical: 8, alignItems: 'center' },
  materialQuickButtonDisabled: { opacity: 0.45 },
  materialQuickButtonText: { fontFamily: font, color: colors.primaryDark, fontSize: 12 },
  materialQuickButtonSecondary: { flex: 1, backgroundColor: '#F6F7F9', borderRadius: 8, paddingVertical: 8, alignItems: 'center', borderWidth: 1, borderColor: colors.borderSoft },
  materialQuickButtonSecondaryText: { fontFamily: font, color: colors.sub, fontSize: 12 },
  detailDivider: { height: 1, backgroundColor: colors.borderSoft, marginVertical: 14 },
  materialCardPreview: { backgroundColor: '#FAFBFF', borderRadius: 8, borderWidth: 1, borderColor: '#E6EEFF', padding: 12, marginBottom: 8 },
  materialViewAllCardsButton: { minHeight: 38, borderRadius: 9, backgroundColor: colors.chip, alignItems: 'center', justifyContent: 'center', marginBottom: 10 },
  materialViewAllCardsText: { fontFamily: font, color: colors.primaryDark, fontSize: 12 },
  importProcessingCard: { flexDirection: 'row', alignItems: 'center', gap: 12, backgroundColor: '#FFF8EE', borderRadius: 10, borderWidth: 1, borderColor: '#FFD9A6', padding: 12, marginBottom: 10 },
  importProcessingPulse: { width: 34, height: 34, borderRadius: 17, backgroundColor: colors.orange, alignItems: 'center', justifyContent: 'center' },
  importProcessingPulseText: { fontFamily: font, color: '#FFFFFF', fontSize: 18, marginTop: -4 },
  importSheetIntro: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#F8FAFF', borderRadius: 12, borderWidth: 1, borderColor: '#D8E8FF', padding: 12, marginBottom: 10 },
  importSheetIntroDot: { width: 26, height: 26, borderRadius: 13, backgroundColor: colors.primary, borderWidth: 6, borderColor: '#D8E8FF' },
  importStepRail: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FAFBFC', borderRadius: 10, borderWidth: 1, borderColor: colors.borderSoft, paddingHorizontal: 9, paddingVertical: 8, marginBottom: 10 },
  importStepItem: { alignItems: 'center', justifyContent: 'center', minWidth: 46 },
  importStepIndex: { fontFamily: font, width: 18, height: 18, borderRadius: 9, backgroundColor: colors.chip, color: colors.primaryDark, textAlign: 'center', lineHeight: 18, fontSize: 10, marginBottom: 3, overflow: 'hidden' },
  importStepText: { fontFamily: font, color: colors.sub, fontSize: 10 },
  importStepLine: { flex: 1, height: 1, backgroundColor: colors.borderSoft, marginHorizontal: 2, marginBottom: 16 },
  importPrimaryStack: { gap: 8, marginBottom: 8 },
  importGroupPanel: { backgroundColor: '#F8FAFF', borderRadius: 12, borderWidth: 1, borderColor: '#D8E8FF', padding: 10, marginBottom: 10 },
  importGroupPanelTeal: { backgroundColor: '#F0FCF9', borderRadius: 12, borderWidth: 1, borderColor: '#BEEADF', padding: 10, marginBottom: 10 },
  importGroupPanelOrange: { backgroundColor: '#FFF8EE', borderRadius: 12, borderWidth: 1, borderColor: '#FFD9A6', padding: 10, marginBottom: 10 },
  importPrimary: { backgroundColor: '#fff', borderRadius: 10, paddingHorizontal: 10, paddingVertical: 9, borderWidth: 1, borderColor: colors.borderSoft, flexDirection: 'row', alignItems: 'center', gap: 10 },
  importPrimaryIcon: { width: 38, height: 38, borderRadius: 9, alignItems: 'center', justifyContent: 'center' },
  importPrimaryIcon_blue: { backgroundColor: colors.chip },
  importPrimaryIcon_teal: { backgroundColor: '#DDF8F3' },
  importPrimaryIcon_orange: { backgroundColor: '#FFF0D6' },
  importPrimaryIconText: { fontFamily: font, fontSize: 18 },
  importPrimaryIconText_blue: { color: colors.primaryDark },
  importPrimaryIconText_teal: { color: '#087A7D' },
  importPrimaryIconText_orange: { color: '#B95E00' },
  importGlyphDocFold: { position: 'absolute', right: 11, top: 10, width: 8, height: 8, borderTopWidth: 2, borderRightWidth: 2, borderColor: colors.primaryDark },
  importGlyphLine: { width: 18, height: 2, borderRadius: 99, backgroundColor: colors.primaryDark, marginBottom: 6 },
  importGlyphLineShort: { width: 12, height: 2, borderRadius: 99, backgroundColor: colors.primaryDark },
  importGlyphCameraBody: { width: 23, height: 16, borderRadius: 5, borderWidth: 2, borderColor: '#087A7D' },
  importGlyphCameraLens: { position: 'absolute', width: 8, height: 8, borderRadius: 4, borderWidth: 2, borderColor: '#087A7D' },
  importGlyphCameraTop: { position: 'absolute', top: 9, left: 11, width: 10, height: 4, borderTopLeftRadius: 4, borderTopRightRadius: 4, backgroundColor: '#087A7D' },
  importGlyphImageFrame: { width: 23, height: 18, borderRadius: 5, borderWidth: 2, borderColor: '#087A7D' },
  importGlyphImageSun: { position: 'absolute', right: 10, top: 10, width: 5, height: 5, borderRadius: 3, backgroundColor: '#087A7D' },
  importGlyphImageMountain: { position: 'absolute', bottom: 11, width: 14, height: 8, borderLeftWidth: 2, borderBottomWidth: 2, borderColor: '#087A7D', transform: [{ rotate: '-35deg' }] },
  importGlyphFolderTab: { position: 'absolute', left: 10, top: 11, width: 12, height: 6, borderTopLeftRadius: 4, borderTopRightRadius: 4, backgroundColor: '#B95E00' },
  importGlyphFolderBody: { width: 24, height: 17, borderRadius: 5, borderWidth: 2, borderColor: '#B95E00', marginTop: 4 },
  importPrimaryTitle: { fontFamily: font, color: colors.text, fontSize: 15, marginBottom: 1 },
  importPrimaryRight: { minWidth: 54, flexDirection: 'row', alignItems: 'center', justifyContent: 'flex-end', gap: 6 },
  importPrimaryMeta: { fontFamily: font, color: colors.primaryDark, fontSize: 12 },
  importAlbumShortcut: { minHeight: 38, borderRadius: 9, borderWidth: 1, borderColor: '#BEEADF', backgroundColor: '#F0FCF9', paddingHorizontal: 11, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 8 },
  importAlbumShortcutText: { fontFamily: font, color: '#087A7D', fontSize: 13 },
  importAlbumShortcutMeta: { fontFamily: font, color: colors.sub, fontSize: 11 },
  importLocalHint: { fontFamily: font, color: colors.sub, fontSize: 11, lineHeight: 17, backgroundColor: '#FAFBFC', borderRadius: 8, borderWidth: 1, borderColor: colors.borderSoft, paddingHorizontal: 10, paddingVertical: 8 },
  importChevron: { fontFamily: font, color: colors.muted, fontSize: 24, lineHeight: 26 },
  importFlowCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#FAFBFC', borderRadius: 10, padding: 12, borderWidth: 1, borderColor: colors.borderSoft, marginBottom: 12 },
  pipelineStep: { paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: colors.borderSoft },
  previewReadyCard: { backgroundColor: '#FFFDF8', borderRadius: 12, borderWidth: 1, borderColor: '#EAE2D2', padding: 14, marginBottom: 10, ...shadow },
  previewReadyBadge: { width: 68, height: 68, borderRadius: 14, backgroundColor: '#F0FCF9', borderWidth: 1, borderColor: '#BEEADF', alignItems: 'center', justifyContent: 'center' },
  previewReadyBadgeValue: { fontFamily: font, color: '#087A7D', fontSize: 22 },
  previewReadyBadgeLabel: { fontFamily: font, color: colors.sub, fontSize: 11 },
  previewFlow: { flexDirection: 'row', alignItems: 'center', marginTop: 12 },
  previewFlowStepDone: { backgroundColor: '#DDF8F3', borderRadius: 99, paddingHorizontal: 9, paddingVertical: 5 },
  previewFlowStepNow: { backgroundColor: colors.chip, borderRadius: 99, paddingHorizontal: 9, paddingVertical: 5 },
  previewFlowStepDoneMuted: { backgroundColor: '#F2F3F5', borderRadius: 99, paddingHorizontal: 9, paddingVertical: 5 },
  previewFlowTextDone: { fontFamily: font, color: '#087A7D', fontSize: 11 },
  previewFlowTextNow: { fontFamily: font, color: colors.primaryDark, fontSize: 11 },
  previewFlowTextMuted: { fontFamily: font, color: colors.muted, fontSize: 11 },
  previewFlowLine: { flex: 1, height: 1, backgroundColor: colors.borderSoft },
  editorSampleButton: { minHeight: 48, borderRadius: 10, borderWidth: 1, borderColor: '#BFE5DC', backgroundColor: '#F0FCF9', paddingHorizontal: 12, marginBottom: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  editorSampleButtonText: { fontFamily: font, color: '#087A7D', fontSize: 14 },
  editorSampleButtonMeta: { fontFamily: font, color: colors.sub, fontSize: 12 },
  previewReadyActions: { marginTop: 12, gap: 7 },
  previewSavingStrip: { flexDirection: 'row', alignItems: 'center', gap: 10, backgroundColor: '#F0FCF9', borderRadius: 10, borderWidth: 1, borderColor: '#BEEADF', padding: 10, marginTop: 12 },
  previewSavingPulse: { width: 28, height: 28, borderRadius: 14, backgroundColor: colors.teal, borderWidth: 6, borderColor: '#DDF8F3' },
  previewStepChips: { flexDirection: 'row', flexWrap: 'wrap', gap: 7, marginBottom: 10 },
  previewStepChip: { backgroundColor: '#F6F7F9', borderRadius: 99, borderWidth: 1, borderColor: colors.borderSoft, paddingHorizontal: 9, paddingVertical: 5 },
  previewStepChipText: { fontFamily: font, color: colors.sub, fontSize: 11 },
  previewRestoreButton: { backgroundColor: colors.chip, borderRadius: 8, paddingHorizontal: 10, paddingVertical: 7 },
  previewRestoreText: { fontFamily: font, color: colors.primaryDark, fontSize: 12 },
  previewEmptyDrafts: { backgroundColor: '#FFF8EE', borderRadius: 10, borderWidth: 1, borderColor: '#FFD9A6', padding: 14, marginBottom: 10, gap: 8 },
  previewDraftRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, backgroundColor: '#FFFFFF', borderRadius: 10, borderWidth: 1, borderColor: colors.borderSoft, padding: 12, marginBottom: 8 },
  previewDraftIndex: { width: 28, height: 28, borderRadius: 14, backgroundColor: colors.chip, alignItems: 'center', justifyContent: 'center' },
  previewDraftIndexText: { fontFamily: font, color: colors.primaryDark, fontSize: 12 },
  previewDraftActions: { width: 48, gap: 6 },
  previewDraftDelete: { minHeight: 30, borderRadius: 8, backgroundColor: '#FFF7F7', borderWidth: 1, borderColor: '#F3C2C2', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4 },
  previewDraftDeleteText: { fontFamily: font, color: colors.red, fontSize: 12 },
  previewDraftMerge: { minHeight: 30, borderRadius: 8, backgroundColor: '#F4FAFF', borderWidth: 1, borderColor: '#CFE2FF', alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4 },
  previewDraftMergeText: { fontFamily: font, color: colors.primaryDark, fontSize: 12 },
  previewDraftInvalid: { minHeight: 30, borderRadius: 8, backgroundColor: '#F3F4F6', borderWidth: 1, borderColor: colors.borderSoft, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 4 },
  previewDraftInvalidText: { fontFamily: font, color: colors.muted, fontSize: 12 },
  editorStageCard: { backgroundColor: '#F8FAFF', borderRadius: 12, borderWidth: 1, borderColor: '#D8E8FF', padding: 12, marginBottom: 10 },
  sheetRoot: { flex: 1, justifyContent: 'flex-end' },
  sheetBackdrop: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0, backgroundColor: 'rgba(31,35,41,0.28)' },
  sheetBackdropTouchable: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0 },
  sheet: { maxHeight: '86%', backgroundColor: colors.card, borderTopLeftRadius: 16, borderTopRightRadius: 16, paddingHorizontal: 16, paddingTop: 10, paddingBottom: 24 },
  sheetGrabber: { alignSelf: 'center', width: 36, height: 4, borderRadius: 99, backgroundColor: colors.border, marginBottom: 8 },
  sheetHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginBottom: 8 },
  sheetClose: { paddingHorizontal: 10, paddingVertical: 8, borderRadius: 6, backgroundColor: '#F2F3F5' },
  sheetCloseText: { fontFamily: font, color: colors.sub, fontSize: 12 },
  sheetBody: { paddingBottom: 12 },
  sheetBodyContent: { paddingBottom: 56 },
  materialBodyInput: { minHeight: 260, textAlignVertical: 'top' },
  reviewScroll: { flex: 1 },
  reviewContainer: { padding: 16, paddingTop: 48, paddingBottom: 28 },
  reviewContainerWithDock: { paddingBottom: 148 },
  reviewTopBar: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  reviewNavButton: { width: 42, height: 42, borderRadius: 12, alignItems: 'center', justifyContent: 'center' },
  reviewNavText: { fontFamily: font, color: colors.text, fontSize: 34, lineHeight: 36 },
  reviewBackGlyph: { width: 24, height: 24, justifyContent: 'center' },
  reviewBackStem: { position: 'absolute', left: 4, width: 18, height: 3, borderRadius: 99, backgroundColor: colors.text },
  reviewBackWingTop: { position: 'absolute', left: 3, top: 6, width: 12, height: 3, borderRadius: 99, backgroundColor: colors.text, transform: [{ rotate: '-45deg' }] },
  reviewBackWingBottom: { position: 'absolute', left: 3, bottom: 6, width: 12, height: 3, borderRadius: 99, backgroundColor: colors.text, transform: [{ rotate: '45deg' }] },
  reviewTopTitle: { alignItems: 'center', flex: 1 },
  reviewMenuText: { fontFamily: font, color: colors.text, width: 42, textAlign: 'center', fontSize: 20 },
  reviewReportButton: { minWidth: 64, height: 36, borderRadius: 10, backgroundColor: colors.card, borderWidth: 1, borderColor: colors.borderSoft, alignItems: 'center', justifyContent: 'center', flexDirection: 'row', gap: 6 },
  reviewReportButtonText: { fontFamily: font, color: colors.primaryDark, fontSize: 12 },
  reviewReportGlyph: { width: 16, height: 18, flexDirection: 'row', alignItems: 'flex-end', gap: 2 },
  reviewReportBar: { width: 3, borderRadius: 99, backgroundColor: colors.primaryDark },
  reviewBookGlyph: { width: 28, height: 28, borderRadius: 8, borderWidth: 1, borderColor: '#BEEADF', backgroundColor: '#F0FCF9', alignItems: 'center', justifyContent: 'center', marginRight: 9 },
  reviewBookPageLeft: { position: 'absolute', left: 7, top: 7, width: 7, height: 14, borderRadius: 2, borderWidth: 1, borderColor: '#087A7D', backgroundColor: '#FFFFFF' },
  reviewBookPageRight: { position: 'absolute', right: 7, top: 7, width: 7, height: 14, borderRadius: 2, borderWidth: 1, borderColor: '#087A7D', backgroundColor: '#FFFFFF' },
  reviewBookSpine: { width: 2, height: 15, borderRadius: 99, backgroundColor: '#087A7D' },
  reviewExitHint: { alignSelf: 'flex-start', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 6, backgroundColor: '#EEF3FF', marginTop: 8 },
  reviewExitHintText: { fontFamily: font, color: colors.primaryDark, fontSize: 12 },
  reviewResult: { backgroundColor: '#E9FBF8', borderColor: '#CFF3EF', borderWidth: 1, borderRadius: 12, padding: 12, marginBottom: 10, ...shadow },
  reviewResult_again: { backgroundColor: '#FFF7F7', borderColor: '#F4BCB8' },
  reviewResult_hard: { backgroundColor: '#FFF8EE', borderColor: '#FFD9A6' },
  reviewResult_good: { backgroundColor: '#F0FCF9', borderColor: '#BEEADF' },
  reviewResultHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  reviewResultMark: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center' },
  reviewResultMark_again: { backgroundColor: '#FFE2E0' },
  reviewResultMark_hard: { backgroundColor: '#FFE9C7' },
  reviewResultMark_good: { backgroundColor: '#DDF8F3' },
  reviewResultMarkText: { fontFamily: font, fontSize: 21, lineHeight: 23 },
  reviewResultMarkText_again: { color: colors.red },
  reviewResultMarkText_hard: { color: '#B95E00' },
  reviewResultMarkText_good: { color: '#087A7D' },
  reviewResultText: { fontFamily: font, color: '#087A7D', fontSize: 13 },
  reviewResultText_again: { color: colors.red },
  reviewResultText_hard: { color: '#B95E00' },
  reviewResultText_good: { color: '#087A7D' },
  reviewResultSub: { fontFamily: font, color: colors.sub, fontSize: 12, marginTop: 3 },
  reviewResultProgress: { height: 6, borderRadius: 99, backgroundColor: 'rgba(255,255,255,0.72)', overflow: 'hidden', marginTop: 10 },
  reviewResultProgressFill: { height: 6, borderRadius: 99, backgroundColor: colors.teal },
  reviewResultProgressFill_again: { backgroundColor: colors.red },
  reviewResultProgressFill_hard: { backgroundColor: colors.orange },
  reviewResultProgressFill_good: { backgroundColor: colors.teal },
  reviewResultNextCard: { backgroundColor: 'rgba(255,255,255,0.7)', borderRadius: 8, borderWidth: 1, borderColor: colors.borderSoft, paddingHorizontal: 10, paddingVertical: 8, marginTop: 9 },
  reviewResultNextLabel: { fontFamily: font, color: colors.primaryDark, fontSize: 11, marginBottom: 3 },
  reviewResultNext: { fontFamily: font, color: colors.text, fontSize: 12 },
  reviewResultNextDone: { fontFamily: font, color: colors.sub, fontSize: 12, marginTop: 9 },
  reviewResultDoneActions: { marginTop: 2 },
  reviewResultActionRow: { flexDirection: 'row', gap: 8, marginTop: 9 },
  reviewResultActionPrimary: { flex: 1, minHeight: 38, borderRadius: 9, backgroundColor: colors.primary, alignItems: 'center', justifyContent: 'center' },
  reviewResultActionPrimaryText: { fontFamily: font, color: '#FFFFFF', fontSize: 12 },
  reviewResultActionSecondary: { flex: 1, minHeight: 38, borderRadius: 9, backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: colors.borderSoft, alignItems: 'center', justifyContent: 'center' },
  reviewResultActionSecondaryText: { fontFamily: font, color: colors.text, fontSize: 12 },
  reviewStageRail: { backgroundColor: colors.card, borderRadius: 12, borderWidth: 1, borderColor: colors.borderSoft, padding: 12, marginBottom: 10, ...shadow },
  reviewStageRailHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 10 },
  reviewStageIdentity: { flex: 1, flexDirection: 'row', alignItems: 'center' },
  reviewStageSubject: { fontFamily: font, color: colors.text, fontSize: 14 },
  reviewStageMeta: { fontFamily: font, color: colors.sub, fontSize: 12, marginTop: 2 },
  reviewStageCount: { fontFamily: font, color: colors.primaryDark, fontSize: 18 },
  reviewDeckStatus: { backgroundColor: colors.card, borderRadius: 10, borderWidth: 1, borderColor: colors.borderSoft, padding: 12, marginBottom: 12 },
  reviewFocusBanner: { backgroundColor: '#F0FCF9', borderRadius: 8, borderWidth: 1, borderColor: '#BEEADF', paddingHorizontal: 9, paddingVertical: 7, marginTop: 8 },
  reviewFocusTitle: { fontFamily: font, color: '#087A7D', fontSize: 13 },
  reviewFocusMeta: { fontFamily: font, color: colors.sub, fontSize: 11, marginTop: 2 },
  reviewSegment: { flexDirection: 'row', gap: 6, backgroundColor: '#F2F3F5', borderRadius: 10, padding: 4, marginBottom: 10 },
  reviewCard: { backgroundColor: 'transparent', borderRadius: 12, marginTop: 2, marginBottom: 12 },
  reviewTransitionOverlay: { position: 'absolute', left: 18, right: 18, top: 154, zIndex: 10, minHeight: 118, borderRadius: 16, borderWidth: 1, alignItems: 'center', justifyContent: 'center', padding: 14, ...shadow },
  reviewTransitionOverlay_again: { backgroundColor: '#FFF7F7', borderColor: '#F4BCB8' },
  reviewTransitionOverlay_hard: { backgroundColor: '#FFF8EE', borderColor: '#FFD9A6' },
  reviewTransitionOverlay_good: { backgroundColor: '#F0FCF9', borderColor: '#BEEADF' },
  reviewTransitionMark: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center', marginBottom: 8 },
  reviewTransitionTitle: { fontFamily: font, fontSize: 15, marginBottom: 3 },
  reviewTransitionSub: { fontFamily: font, color: colors.sub, fontSize: 11 },
  reviewFlipArea: { minHeight: 308, paddingBottom: 10 },
  reviewFlipAreaAnswer: { minHeight: 520 },
  reviewDeckLayer: { position: 'absolute', left: 12, right: 12, borderRadius: 14, borderWidth: 1, borderColor: '#EAE2D2', backgroundColor: 'rgba(255,253,248,0.82)' },
  reviewDeckLayerBack: { top: 16, bottom: 0, transform: [{ scale: 0.94 }] },
  reviewDeckLayerMid: { top: 8, bottom: 6, transform: [{ scale: 0.97 }] },
  reviewFlipFace: { minHeight: 308, borderRadius: 14, backfaceVisibility: 'hidden' },
  reviewFlipBack: { position: 'absolute', left: 0, right: 0, top: 0, bottom: 0 },
  reviewFace: { minHeight: 308, borderRadius: 14, backgroundColor: '#FFFDF8', borderWidth: 1, borderTopWidth: 4, borderColor: '#EAE2D2', justifyContent: 'space-between', overflow: 'hidden', ...shadow },
  reviewFaceRevealed: { minHeight: 520, backgroundColor: '#FFFDF8', borderColor: '#EAE2D2', justifyContent: 'flex-start' },
  reviewPaperBgWrap: { flex: 1 },
  reviewPaperBg: { flex: 1, minHeight: 304, padding: 14, justifyContent: 'space-between' },
  reviewPaperBgImage: { opacity: 0.72 },
  reviewCardWatermark: { position: 'absolute', right: 16, bottom: 86, fontFamily: font, fontSize: 32, opacity: 0.1 },
  reviewStar: { fontFamily: font, color: colors.muted, fontSize: 28, lineHeight: 28 },
  reviewSummary: { backgroundColor: '#F8FAFF', borderRadius: 8, borderWidth: 1, borderColor: '#E6EEFF', padding: 12, marginBottom: 10, flexDirection: 'row', alignItems: 'center', gap: 10 },
  reviewSummaryImage: { width: 74, height: 54, borderRadius: 8, backgroundColor: colors.panel },
  reviewCompletePanel: { backgroundColor: colors.card, borderRadius: 14, borderWidth: 1, borderColor: colors.borderSoft, padding: 14, marginBottom: 12, ...shadow },
  reviewCompleteQuickExit: { flexDirection: 'row', gap: 8, marginBottom: 10 },
  reviewCompleteQuickButton: { flex: 1, minHeight: 42, borderRadius: 10, backgroundColor: '#F6F7F9', borderWidth: 1, borderColor: colors.borderSoft, alignItems: 'center', justifyContent: 'center' },
  reviewCompleteQuickButtonPrimary: { backgroundColor: colors.chip, borderColor: '#D8E8FF' },
  reviewCompleteQuickButtonText: { fontFamily: font, color: colors.sub, fontSize: 13 },
  reviewCompleteQuickButtonTextPrimary: { fontFamily: font, color: colors.primaryDark, fontSize: 13 },
  reviewCompleteImage: { width: '100%', height: 118, borderRadius: 10, backgroundColor: colors.panel, marginBottom: 12 },
  reviewCompleteStats: { flexDirection: 'row', gap: 8, marginTop: 12, marginBottom: 4 },
  reviewCompleteFlow: { flexDirection: 'row', alignItems: 'center', marginTop: 12 },
  reviewCompleteFlowStepDone: { backgroundColor: '#DDF8F3', borderRadius: 99, paddingHorizontal: 11, paddingVertical: 6 },
  reviewCompleteFlowStepNow: { backgroundColor: colors.chip, borderRadius: 99, paddingHorizontal: 11, paddingVertical: 6 },
  reviewCompleteFlowTextDone: { fontFamily: font, color: '#087A7D', fontSize: 12 },
  reviewCompleteFlowTextNow: { fontFamily: font, color: colors.primaryDark, fontSize: 12 },
  reviewCompleteFlowLine: { flex: 1, height: 1, backgroundColor: colors.borderSoft },
  coachReportPanel: { backgroundColor: '#FFFDF8', borderRadius: 12, borderWidth: 1, borderColor: '#EAE2D2', padding: 14, marginBottom: 10, ...shadow },
  coachReportBadge: { width: 74, height: 74, borderRadius: 14, backgroundColor: '#FFF7ED', borderWidth: 1, borderColor: '#FFE1B8', alignItems: 'center', justifyContent: 'center' },
  coachReportBadgeValue: { fontFamily: font, color: '#B95E00', fontSize: 22 },
  coachReportBadgeLabel: { fontFamily: font, color: colors.sub, fontSize: 11 },
  reviewProgressTrack: { height: 6, backgroundColor: '#EDF1F7', borderRadius: 99, overflow: 'hidden', marginTop: 10 },
  reviewProgressFill: { height: 6, backgroundColor: colors.teal, borderRadius: 99 },
  reviewPrompt: { fontFamily: brandFont, color: colors.text, fontSize: 19, lineHeight: 29, marginTop: 12, marginBottom: 10 },
  reviewTapHint: { fontFamily: font, color: colors.muted, fontSize: 12, marginTop: 8 },
  answerPanel: { backgroundColor: '#FFFFFF', borderRadius: 12, padding: 10, marginTop: 8, borderWidth: 1, borderColor: colors.borderSoft },
  answerPanelHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, marginBottom: 8 },
  answerFlow: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
  answerFlowStepActive: { backgroundColor: '#E9FBF8', borderRadius: 99, paddingHorizontal: 10, paddingVertical: 5 },
  answerFlowStepIdle: { backgroundColor: '#F2F3F5', borderRadius: 99, paddingHorizontal: 10, paddingVertical: 5 },
  answerFlowTextActive: { fontFamily: font, color: '#087A7D', fontSize: 11 },
  answerFlowTextIdle: { fontFamily: font, color: colors.muted, fontSize: 11 },
  answerFlowLine: { flex: 1, height: 1, backgroundColor: colors.borderSoft },
  reviewAnswerTitle: { fontFamily: font, color: colors.primaryDark, fontSize: 18 },
  reviewAnswerText: { fontFamily: font, color: colors.text, fontSize: 14, lineHeight: 22 },
  reviewAnswerBadge: { fontFamily: font, color: '#087A7D', backgroundColor: '#E9FBF8', borderRadius: 6, paddingHorizontal: 8, paddingVertical: 4, fontSize: 11 },
  reviewAnswerSections: { gap: 10 },
  reviewAnswerSection: { backgroundColor: '#FFFFFF', borderWidth: 1, borderColor: '#E8EEF8', borderRadius: 10, padding: 12 },
  reviewAnswerSectionSoft: { backgroundColor: '#F0FCFA', borderWidth: 1, borderColor: '#BCEDE7', borderRadius: 10, padding: 12 },
  reviewAnswerSectionWarn: { backgroundColor: '#FFF7E8', borderWidth: 1, borderColor: '#FFDDB2', borderRadius: 10, padding: 12 },
  reviewAnswerSectionTitle: { fontFamily: font, color: colors.muted, fontSize: 12, marginBottom: 6 },
  reviewSelfCheck: { marginTop: 10, paddingTop: 9, borderTopWidth: 1, borderTopColor: colors.borderSoft },
  reviewCheckChip: { backgroundColor: '#EAF2FF', borderRadius: 99, paddingHorizontal: 10, paddingVertical: 6, marginRight: 6, marginBottom: 6 },
  reviewCheckChipText: { fontFamily: font, color: colors.primaryDark, fontSize: 12 },
  answerDecisionHint: { marginTop: 10, backgroundColor: '#F8FAFF', borderRadius: 10, borderWidth: 1, borderColor: '#E6EEFF', padding: 10 },
  answerDecisionTitle: { fontFamily: font, color: colors.primaryDark, fontSize: 13, marginBottom: 3 },
  answerDecisionText: { fontFamily: font, color: colors.sub, fontSize: 12, lineHeight: 18 },
  answerQuickScore: { marginTop: 12, paddingTop: 12, borderTopWidth: 1, borderTopColor: colors.borderSoft },
  answerQuickScoreRow: { flexDirection: 'row', gap: 8, marginTop: 10 },
  answerQuickScoreButton: { flex: 1, minHeight: 58, borderRadius: 10, borderWidth: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6, paddingVertical: 8 },
  answerQuickScoreButtonRed: { backgroundColor: '#FFF7F7', borderColor: '#F4BCB8' },
  answerQuickScoreButtonOrange: { backgroundColor: '#FFF8EE', borderColor: '#FFD9A6' },
  answerQuickScoreButtonTeal: { backgroundColor: '#F0FCF9', borderColor: '#BEEADF' },
  answerQuickScoreButton_again: { backgroundColor: '#FFF7F7', borderColor: '#F4BCB8' },
  answerQuickScoreButton_hard: { backgroundColor: '#FFF8EE', borderColor: '#FFD9A6' },
  answerQuickScoreButton_good: { backgroundColor: '#F0FCF9', borderColor: '#BEEADF' },
  answerQuickScoreDisabled: { opacity: 0.55 },
  answerQuickScoreText: { fontFamily: font, fontSize: 15, marginBottom: 3 },
  answerQuickScoreTextRed: { color: colors.red },
  answerQuickScoreTextOrange: { color: '#B95E00' },
  answerQuickScoreTextTeal: { color: '#087A7D' },
  answerQuickScoreText_again: { color: colors.red },
  answerQuickScoreText_hard: { color: '#B95E00' },
  answerQuickScoreText_good: { color: '#087A7D' },
  answerQuickScoreSub: { fontFamily: font, color: colors.sub, fontSize: 10 },
  reviewUtilityRow: { flexDirection: 'row', gap: 8, marginTop: 10 },
  reviewStickyScoreDock: { position: 'absolute', left: 12, right: 12, bottom: 12, backgroundColor: '#FFFFFF', borderRadius: 12, borderWidth: 1, borderTopWidth: 3, borderColor: colors.borderSoft, borderTopColor: colors.primary, padding: 12, ...shadow },
  reviewStickyScoreHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8 },
  reviewScoreDock: { backgroundColor: '#FFFFFF', borderRadius: 14, borderWidth: 1, borderTopWidth: 4, borderColor: colors.borderSoft, borderTopColor: colors.teal, padding: 12, marginTop: 10, ...shadow },
  reviewMemoryRail: { flexDirection: 'row', alignItems: 'center', marginTop: 12, marginBottom: 8 },
  reviewMemoryStep: { minWidth: 70, minHeight: 42, borderRadius: 11, borderWidth: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 6 },
  reviewMemoryStepRed: { backgroundColor: '#FFF7F7', borderColor: '#F4BCB8' },
  reviewMemoryStepOrange: { backgroundColor: '#FFF8EE', borderColor: '#FFD9A6' },
  reviewMemoryStepTeal: { backgroundColor: '#F0FCF9', borderColor: '#BEEADF' },
  reviewMemoryLine: { flex: 1, height: 1, backgroundColor: colors.borderSoft },
  reviewMemoryMarkRed: { fontFamily: font, color: colors.red, fontSize: 16, lineHeight: 18 },
  reviewMemoryMarkOrange: { fontFamily: font, color: '#B95E00', fontSize: 16, lineHeight: 18 },
  reviewMemoryMarkTeal: { fontFamily: font, color: '#087A7D', fontSize: 16, lineHeight: 18 },
  reviewMemoryText: { fontFamily: font, color: colors.sub, fontSize: 10, marginTop: 1 },
  reviewScoreRow: { flexDirection: 'row', gap: 8, marginTop: 12 },
  reviewScoreButton: { flex: 1, minHeight: 104, borderRadius: 13, borderWidth: 1, alignItems: 'center', justifyContent: 'center', paddingHorizontal: 7, paddingVertical: 10 },
  reviewScoreButton_red: { backgroundColor: '#FFF7F7', borderColor: '#F4BCB8' },
  reviewScoreButton_orange: { backgroundColor: '#FFF8EE', borderColor: '#FFD9A6' },
  reviewScoreButton_teal: { backgroundColor: '#F0FCF9', borderColor: '#BEEADF' },
  reviewScoreFace: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', marginBottom: 7 },
  reviewScoreFace_red: { backgroundColor: '#FFE2E0' },
  reviewScoreFace_orange: { backgroundColor: '#FFE9C7' },
  reviewScoreFace_teal: { backgroundColor: '#DDF8F3' },
  reviewScoreFaceText: { fontFamily: font, fontSize: 20, lineHeight: 23 },
  reviewScoreFaceText_red: { color: colors.red },
  reviewScoreFaceText_orange: { color: '#B95E00' },
  reviewScoreFaceText_teal: { color: '#087A7D' },
  reviewScoreTitle: { fontFamily: font, fontSize: 17, marginBottom: 4 },
  reviewScoreTitle_red: { color: colors.red },
  reviewScoreTitle_orange: { color: '#B95E00' },
  reviewScoreTitle_teal: { color: '#087A7D' },
  reviewScoreSub: { fontFamily: font, color: colors.sub, fontSize: 11 },
  reviewInlineReport: { backgroundColor: '#FFFFFF', borderRadius: 12, borderWidth: 1, borderColor: colors.borderSoft, padding: 12, marginTop: 10, marginBottom: 2, ...shadow },
  reviewInlineReportToggle: { fontFamily: font, color: colors.text, fontSize: 18, lineHeight: 20 },
  reviewInlineReportStats: { flexDirection: 'row', alignItems: 'stretch', gap: 7, marginTop: 10 },
  reviewInlineReportStat: { flex: 1, minHeight: 78, borderRadius: 10, borderWidth: 1, borderColor: colors.borderSoft, backgroundColor: '#FAFBFC', paddingHorizontal: 8, paddingVertical: 9, justifyContent: 'center' },
  reviewInlineReportValue: { fontFamily: font, color: colors.text, fontSize: 21, marginBottom: 4 },
  reviewInlineReportLabel: { fontFamily: font, color: colors.sub, fontSize: 11, marginBottom: 4 },
  reviewInlineReportDelta: { fontFamily: font, color: '#087A7D', fontSize: 10 },
  reviewInlineReportTrend: { width: 84, minHeight: 78, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', backgroundColor: '#F0FCF9', borderRadius: 10, borderWidth: 1, borderColor: '#BEEADF', paddingHorizontal: 9, paddingVertical: 9 },
  reviewInlineReportBar: { width: 8, borderRadius: 99, backgroundColor: colors.teal },
  reviewReportStatsRow: { flexDirection: 'row', backgroundColor: '#FFFFFF', borderRadius: 10, borderWidth: 1, borderColor: colors.borderSoft, paddingVertical: 12, marginTop: 12, marginBottom: 10 },
  reviewReportStat: { flex: 1, alignItems: 'center', paddingHorizontal: 6 },
  reviewReportStatDivider: { width: 1, backgroundColor: colors.borderSoft },
  reviewReportStatLabel: { fontFamily: font, color: colors.sub, fontSize: 11, marginBottom: 6 },
  reviewReportStatValue: { fontFamily: font, color: colors.text, fontSize: 18 },
  reportTrendCard: { backgroundColor: '#F8FAFF', borderRadius: 10, borderWidth: 1, borderColor: '#E6EEFF', padding: 12, marginBottom: 10, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  reportTrendBars: { height: 86, flexDirection: 'row', alignItems: 'flex-end', gap: 8 },
  reportTrendBarSlot: { width: 20, alignItems: 'center', justifyContent: 'flex-end', gap: 5 },
  reportTrendBar: { width: 8, borderRadius: 99, backgroundColor: colors.teal },
  reportItem: { paddingVertical: 10, borderTopWidth: 1, borderTopColor: colors.borderSoft },
});
